backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"       # Relative to repo root (in public)
public_folder: "/assets/uploads"     # Public URL

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
